
{
  "masonryId": "view-all-works",
  "initialPortion": {
    "items": {
      "_t": "System.Linq.Enumerable+WhereSelectArrayIterator`2[[Wikipaintings.Mongo.Model.MongoPainting, Wikipaintings.Mongo],[Wikipaintings.Web.Models.Partials.PaintingForGalleryNew, Wikipaintings.Web]]",
      "_v": [
        {
          "_id": "57fbacfaedc2c95dd0c8358b",
          "title": "The Valve",
          "year": "1954",
          "width": 888,
          "height": 1100,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads6.wikiart.org/00101/images/roy-lichtenstein/c5ddc76ac97eea916dd733efd4b55fe0.jpg",
          "map": "01234*67*",
          "paintingUrl": "/en/roy-lichtenstein/the-valve-1954",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "5f4de549edc2c9719c2f0f3c",
          "title": "Mickey Mouse I",
          "year": "1958",
          "width": 842,
          "height": 650,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads5.wikiart.org/00304/images/roy-lichtenstein/4050.jpg",
          "map": "0123**67*",
          "paintingUrl": "/en/roy-lichtenstein/mickey-mouse-i-1958",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "614d026c9e43631dacba9c39",
          "title": "I Can See the Whole Room...and There's Nobody in It!",
          "year": "1961",
          "width": 316,
          "height": 316,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads3.wikiart.org/00359/images/roy-lichtenstein/i-can-see-the-whole-room.jpg",
          "map": "**2***67*",
          "paintingUrl": "/en/roy-lichtenstein/i-can-see-the-whole-room-and-theres-nobody-in-it-1961",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4aedc2cb3880b69f43",
          "title": "Bread in bag",
          "year": "1961",
          "width": 548,
          "height": 275,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads4.wikiart.org/images/roy-lichtenstein/bread-in-bag-1961.jpg",
          "map": "0*23**67*",
          "paintingUrl": "/en/roy-lichtenstein/bread-in-bag-1961",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4bedc2cb3880b6a073",
          "title": "Girl with ball",
          "year": "1961",
          "width": 303,
          "height": 504,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads0.wikiart.org/images/roy-lichtenstein/girl-with-ball-1961(1).jpg",
          "map": "0*23**67*",
          "paintingUrl": "/en/roy-lichtenstein/girl-with-ball-1961",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4cedc2cb3880b6a203",
          "title": "Look Mickey",
          "year": "1961",
          "width": 432,
          "height": 300,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads6.wikiart.org/images/roy-lichtenstein/look-mickey-1961(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/look-mickey-1961",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4dedc2cb3880b6a2d3",
          "title": "Mr. Bellamy",
          "year": "1961",
          "width": 312,
          "height": 432,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads5.wikiart.org/images/roy-lichtenstein/mr-bellamy-1961(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/mr-bellamy-1961",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4dedc2cb3880b6a373",
          "title": "Roto Broil",
          "year": "1961",
          "width": 432,
          "height": 422,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads5.wikiart.org/images/roy-lichtenstein/roto-broil-1961(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/roto-broil-1961",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4eedc2cb3880b6a473",
          "title": "Washing machine",
          "year": "1961",
          "width": 432,
          "height": 347,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads7.wikiart.org/images/roy-lichtenstein/washing-machine-1961.jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/washing-machine-1961",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "5f4dfbabedc2c9719cbb3190",
          "title": "Tex!",
          "year": "1962",
          "width": 842,
          "height": 716,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads6.wikiart.org/00304/images/roy-lichtenstein/20528.jpg",
          "map": "0123**67*",
          "paintingUrl": "/en/roy-lichtenstein/tex-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4aedc2cb3880b69f03",
          "title": "Baked potato",
          "year": "1962",
          "width": 432,
          "height": 288,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads7.wikiart.org/images/roy-lichtenstein/baked-potato-1962(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/baked-potato-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4aedc2cb3880b69f13",
          "title": "Baked potato",
          "year": "1962",
          "width": 432,
          "height": 317,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads6.wikiart.org/images/roy-lichtenstein/baked-potato-1962-1.jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/baked-potato-1962-1",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4aedc2cb3880b69f33",
          "title": "Blam",
          "year": "1962",
          "width": 587,
          "height": 504,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads8.wikiart.org/images/roy-lichtenstein/blam-1962(1).jpg",
          "map": "0*23**67*",
          "paintingUrl": "/en/roy-lichtenstein/blam-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4bedc2cb3880b69fe3",
          "title": "Curtains",
          "year": "1962",
          "width": 362,
          "height": 432,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads3.wikiart.org/images/roy-lichtenstein/curtains-1962(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/curtains-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4bedc2cb3880b69ff3",
          "title": "Desk calendar",
          "year": "1962",
          "width": 449,
          "height": 309,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads8.wikiart.org/images/roy-lichtenstein/desk-calendar-1962(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/desk-calendar-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4bedc2cb3880b6a043",
          "title": "Forget it! Forget me!",
          "year": "1962",
          "width": 369,
          "height": 432,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads5.wikiart.org/images/roy-lichtenstein/forget-it-forget-me-1962(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/forget-it-forget-me-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4bedc2cb3880b6a0c3",
          "title": "Head - red and yellow",
          "year": "1962",
          "width": 432,
          "height": 431,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads5.wikiart.org/images/roy-lichtenstein/head-red-and-yellow-1962(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/head-red-and-yellow-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4cedc2cb3880b6a183",
          "title": "Jet pilot",
          "year": "1962",
          "width": 478,
          "height": 432,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads1.wikiart.org/images/roy-lichtenstein/jet-pilot-1962.jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/jet-pilot-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4cedc2cb3880b6a1a3",
          "title": "Kitchen range",
          "year": "1961-1962",
          "width": 432,
          "height": 430,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads8.wikiart.org/images/roy-lichtenstein/kitchen-range-1962(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/kitchen-range-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        },
        {
          "_id": "57726e4cedc2cb3880b6a1f3",
          "title": "Live ammo (Ha! Ha! Ha!)",
          "year": "1962",
          "width": 435,
          "height": 432,
          "artistName": "Roy Lichtenstein",
          "image": "https://uploads4.wikiart.org/images/roy-lichtenstein/live-ammo-ha-ha-ha-1962(1).jpg",
          "map": "**23**67*",
          "paintingUrl": "/en/roy-lichtenstein/live-ammo-ha-ha-ha-1962",
          "artistUrl": "/en/roy-lichtenstein",
          "albums": null,
          "flags": 2,
          "images": null
        }
      ]
    },
    "itemsCount": 152
  },
  "filter": {
    "_t": "MenuLinkWithHref",
    "Name": "chronologically",
    "Url": "/en/roy-lichtenstein/mode/all-paintings?json=2",
    "Title": "All Artworks by Date 1→10",
    "ListTitle": "List of works",
    "Quantity": 152,
    "Selected": true,
    "UniqueName": "all-paintings-chronologically"
  }
}

       
       